# Generated by Django 4.2.18 on 2025-02-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='class_status',
            field=models.IntegerField(choices=[(0, 'Confirmed'), (1, 'Cancelled'), (2, 'Completed')], default=0),
        ),
    ]
