# Generated by Django 4.2.18 on 2025-02-02 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='booking',
            name='gym_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='classes.class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.instructor'),
        ),
    ]
