# Generated by Django 4.2.18 on 2025-02-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_class_class_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='repeat_schedule',
            field=models.CharField(blank=True, choices=[(None, 'Does Not Repeat'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10, null=True),
        ),
    ]
