# Generated by Django 4.2.18 on 2025-02-13 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0006_class_repeat_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attended_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
